import type { SkillNode } from './types';

export const skillTree: SkillNode[] = [
  {
    id: 'hvac-basics',
    role: 'HVAC',
    label: 'HVAC Basics',
    description: 'Core system handling, safety, and standard service routines.',
    tier: 1,
    requiredLevel: 1,
    path: 'any',
    requiresSkillIds: [],
  },
  {
    id: 'hvac-diagnostics',
    role: 'HVAC',
    label: 'Diagnostics',
    description: 'Advanced fault tracing and performance evaluation.',
    tier: 2,
    requiredLevel: 4,
    path: 'leveling',
    requiresSkillIds: ['hvac-basics'],
  },
  {
    id: 'hvac-enterprise-ops',
    role: 'HVAC',
    label: 'Fleet Operations',
    description: 'Manage multiple job streams and workforce dispatch.',
    tier: 3,
    requiredLevel: 7,
    path: 'enterprise',
    requiresSkillIds: ['hvac-basics'],
  },
  {
    id: 'construction-basics',
    role: 'Construction',
    label: 'Construction Basics',
    description: 'Foundational production, repair, and site task execution.',
    tier: 1,
    requiredLevel: 1,
    path: 'any',
    requiresSkillIds: [],
  },
  {
    id: 'construction-framing',
    role: 'Construction',
    label: 'Framing Logic',
    description: 'Structured build sequencing and assembly flow.',
    tier: 2,
    requiredLevel: 3,
    path: 'leveling',
    requiresSkillIds: ['construction-basics'],
  },
  {
    id: 'construction-enterprise',
    role: 'Construction',
    label: 'Crew Scaling',
    description: 'Expand from builder to coordinated enterprise execution.',
    tier: 3,
    requiredLevel: 6,
    path: 'enterprise',
    requiresSkillIds: ['construction-basics'],
  },
  {
    id: 'irs-basics',
    role: 'IRS',
    label: 'IRS Basics',
    description: 'Foundational tax routing, review logic, and ledger enforcement.',
    tier: 1,
    requiredLevel: 1,
    path: 'any',
    requiresSkillIds: [],
  },
  {
    id: 'irs-audit',
    role: 'IRS',
    label: 'Audit Chain',
    description: 'Trace suspicious financial flows and validate payout history.',
    tier: 2,
    requiredLevel: 5,
    path: 'enterprise',
    requiresSkillIds: ['irs-basics'],
  },
  {
    id: 'irs-fraud-net',
    role: 'IRS',
    label: 'Fraud Net',
    description: 'Expanded fraud detection and enforcement oversight.',
    tier: 3,
    requiredLevel: 8,
    path: 'enterprise',
    requiresSkillIds: ['irs-audit'],
  },
  {
    id: 'crypto-basics',
    role: 'Crypto',
    label: 'Market Basics',
    description: 'Core liquidity, pricing, and economic signal management.',
    tier: 1,
    requiredLevel: 1,
    path: 'any',
    requiresSkillIds: [],
  },
  {
    id: 'crypto-liquidity',
    role: 'Crypto',
    label: 'Liquidity Routing',
    description: 'Direct internal exchange flow and pool balancing.',
    tier: 2,
    requiredLevel: 4,
    path: 'enterprise',
    requiresSkillIds: ['crypto-basics'],
  },
  {
    id: 'crypto-market-maker',
    role: 'Crypto',
    label: 'Market Maker',
    description: 'Advanced capital balancing and strategic treasury influence.',
    tier: 3,
    requiredLevel: 7,
    path: 'enterprise',
    requiresSkillIds: ['crypto-liquidity'],
  },
  {
    id: 'mapper-basics',
    role: 'Mapper',
    label: 'Mapping Basics',
    description: 'Core route discovery and territory coverage.',
    tier: 1,
    requiredLevel: 1,
    path: 'any',
    requiresSkillIds: [],
  },
  {
    id: 'mapper-routing',
    role: 'Mapper',
    label: 'Routing Logic',
    description: 'Unlock optimized pathing between territories.',
    tier: 2,
    requiredLevel: 3,
    path: 'leveling',
    requiresSkillIds: ['mapper-basics'],
  },
  {
    id: 'mapper-expansion',
    role: 'Mapper',
    label: 'Expansion Grid',
    description: 'Unlock territorial growth and deeper world expansion.',
    tier: 3,
    requiredLevel: 6,
    path: 'enterprise',
    requiresSkillIds: ['mapper-routing'],
  },
];